name: Main workflow

on:
  push:
    branches:
      - "**"

#env:

jobs:
  ##################################################################################################
  ############### CHECKS ###########################################################################
  ##################################################################################################

  run_checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          [
            "make check-end-of-file-fixer",
            "make check-gitleaks",
            "make check-prettier",
            "make check-ruff",
            "make check-trailing-whitespace",
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: "3.10"

      - name: Run command
        run: |
          source .venv-checks/bin/activate
          ${{ matrix.command }}

  ##################################################################################################
  ############### UNIT TESTS #######################################################################
  ##################################################################################################

  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          pytest tests/unit

  ##################################################################################################
  ############### INTEGRATION TESTS ################################################################
  ##################################################################################################

  run_integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run integration tests
        run: |
          source .venv/bin/activate
          pytest tests/integration
